[project]
name = "zinc-flow"
version = "0.1.0"
main = "main.zn"

[go]
version = "1.26"

[deps]
stdlib        = "github.com/ZincScale/zinc-stdlib"
fsnotify      = "github.com/fsnotify/fsnotify@v1.7.0"
klausCompress = "github.com/klauspost/compress@v1.17.9"
zstd          = "github.com/klauspost/compress/zstd"
hambaAvro     = "github.com/hamba/avro/v2@v2.25.0"
hambaOcf      = "github.com/hamba/avro/v2/ocf"
ojg           = "github.com/ohler55/ojg@v1.28.1"
ojgJp         = "github.com/ohler55/ojg/jp"
viper         = "github.com/spf13/viper"
httptest      = "net/http/httptest"

[replace]
stdlib = "../../zinc/compilers/zinc-go/stdlib/zinc-out"
